# Generated by Django 3.0.5 on 2022-01-05 00:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('home_score', models.IntegerField()),
                ('visitor_score', models.IntegerField()),
                ('video_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GameVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos/games/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backoffice.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('status', models.CharField(choices=[('field_player', 'Field Player'), ('goal_keeper', 'Goal Keeper')], max_length=255)),
                ('number', models.IntegerField()),
                ('strong_feet', models.CharField(choices=[('right', 'Right'), ('left', 'Left')], max_length=255)),
                ('height', models.IntegerField()),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backoffice.Country')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.DateField()),
                ('end', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backoffice.Country')),
                ('leagues', models.ManyToManyField(to='backoffice.League')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('status', models.CharField(choices=[('coach', 'Coach'), ('assistant', 'Assistant')], max_length=255)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backoffice.Country')),
                ('current_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backoffice.Team')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlayerActionInGame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_start', models.IntegerField()),
                ('video_end', models.IntegerField()),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backoffice.Action')),
                ('attributes', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backoffice.Attribute')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backoffice.Game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backoffice.Player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backoffice.Team')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='current_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backoffice.Team'),
        ),
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.DateField(null=True)),
                ('end', models.DateField(null=True)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('finished', 'Finished')], default='', max_length=255)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.Player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.Team')),
            ],
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('status', models.BooleanField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='game',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backoffice.League'),
        ),
        migrations.AddField(
            model_name='game',
            name='home',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home', to='backoffice.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backoffice.Season'),
        ),
        migrations.AddField(
            model_name='game',
            name='video',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backoffice.GameVideo'),
        ),
        migrations.AddField(
            model_name='game',
            name='visitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor', to='backoffice.Team'),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin', models.DateField()),
                ('end', models.DateField()),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('finished', 'Finished')], max_length=255)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backoffice.Staff')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.Team')),
            ],
        ),
        migrations.AddField(
            model_name='action',
            name='attributes',
            field=models.ManyToManyField(to='backoffice.Attribute'),
        ),
    ]
