# Generated by Django 3.0.5 on 2022-01-17 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0002_auto_20220105_0105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playeractioningame',
            name='video_end',
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
        migrations.AlterField(
            model_name='playeractioningame',
            name='video_start',
            field=models.DecimalField(decimal_places=4, max_digits=8),
        ),
    ]
